In [1]:
import pandas as pd
irr = pd.read_csv('data/irr.csv')
al = pd.read_csv('data/al.csv')
jm = pd.read_csv('data/jm.csv')

C:\Users\jcorrea\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [3]:
al

,Unnamed: 0,uuid,city,state,country,confidence,location,magvar,thumbs_up,reliability,report_description,report_rating,road_type,street,subtype,type,pub_millis,pub_utc_date
0,0,17ca1b76-3034-37ba-950c-b3aa0853d111,Staten Island,NY,US,0,"{'x': -74.231683, 'y': 40.525413}",73,0,5,NaN,2,4.0,to NY-440 N / W Shore Expwy / Korean War Veter...,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1530846606126,2018-07-05T23:10:06.126000
1,1,6b6006aa-4d6c-3c61-bbf1-48e989d4b53b,Staten Island,NY,US,5,"{'x': -74.19337749481203, 'y': 40.58887928499723}",171,0,10,NaN,0,2.0,NaN,HAZARD_ON_ROAD_CONSTRUCTION,WEATHERHAZARD,1530827975000,2018-07-05T17:59:35
2,2,770cd844-cb83-3414-8444-3bb319d19e4b,Staten Island,NY,US,0,"{'x': -74.19329166412355, 'y': 40.58755123707033}",162,0,7,NaN,0,4.0,to NY-440 S / W Shore Expwy / Outerbridge Xing...,HAZARD_ON_ROAD_CONSTRUCTION,WEATHERHAZARD,1530827993000,2018-07-05T17:59:53
3,3,ca3381b7-0941-3146-9462-f68debddf4c6,Elizabeth,NJ,US,0,"{'x': -74.188656, 'y': 40.685938}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530535478725,2018-07-02T08:44:38.725000
4,4,e8f2eb2a-cfb1-314e-9b06-6bf215b77139,Elizabeth,NJ,US,2,"{'x': -74.191085, 'y': 40.681085}",0,0,10,Construction,0,NaN,Basilone Rd,ROAD_CLOSED_EVENT,ROAD_CLOSED,1526552367451,2018-05-17T06:19:27.451000
5,5,1ece3af1-d4c0-3399-a0b6-c05e1adb55a4,Elizabeth,NJ,US,0,"{'x': -74.189309, 'y': 40.681168}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530422397241,2018-07-01T01:19:57.241000
6,6,3f89ff35-196a-3ac5-ba2d-1ae19a2b7af9,Elizabeth,NJ,US,0,"{'x': -74.188875, 'y': 40.685426}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530422396774,2018-07-01T01:19:56.774000
7,7,2d32afd9-0436-3169-9c3c-8d55da7e41c5,Elizabeth,NJ,US,0,"{'x': -74.189206, 'y': 40.684333}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530422397950,2018-07-01T01:19:57.950000
8,8,32d535c5-4015-3ec2-b8e9-3770525c2540,Elizabeth,NJ,US,0,"{'x': -74.189449, 'y': 40.681968}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530422387958,2018-07-01T01:19:47.958000
9,9,37069b8a-975a-3dd9-adf2-38b5165344fd,Elizabeth,NJ,US,0,"{'x': -74.189072, 'y': 40.684863}",0,0,6,Construction,0,NaN,Earhart Dr,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530535387112,2018-07-02T08:43:07.112000
10,10,eb76c1c9-0c83-3e94-ae16-25fdd30b9bd5,Elizabeth,NJ,US,0,"{'x': -74.192597, 'y': 40.681191}",16,0,5,NaN,1,4.0,to US-1-9 N / Newark,NaN,WEATHERHAZARD,1530846742554,2018-07-05T23:12:22.554000
11,11,00a2486c-467a-3682-9726-c9a874ebff2a,Staten Island,NY,US,0,"{'x': -74.143276, 'y': 40.638685}",0,0,6,Richmond Terrace,0,NaN,Richmond Ter,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796023800,2018-07-05T09:07:03.800000
12,12,062b2fd0-ded3-3840-8560-7df4c651c13b,Bayonne,NJ,US,0,"{'x': -74.140179, 'y': 40.646674}",0,0,6,BB SB Closure,0,NaN,Bayonne Br S,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796024623,2018-07-05T09:07:04.623000
13,13,4efd8189-c26f-30c7-895d-ea43b2c144d6,Bayonne,NJ,US,0,"{'x': -74.143173, 'y': 40.639001}",0,0,6,BB NB Closure,0,NaN,Bayonne Br N,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796024812,2018-07-05T09:07:04.812000
14,14,8cbd6c2d-ce08-3936-b68a-5268a88afd75,Staten Island,NY,US,0,"{'x': -74.143937, 'y': 40.638347}",0,0,6,Richmond Terrace,0,NaN,Richmond Ter,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796024941,2018-07-05T09:07:04.941000
15,15,67b17a92-962e-37d9-a4b2-3bea62ae43ae,Staten Island,NY,US,0,"{'x': -74.144805, 'y': 40.637932}",0,0,6,Richmond Terrace,0,NaN,Richmond Ter,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796025633,2018-07-05T09:07:05.633000
16,16,46853519-cd7d-3eec-9e5e-86c75f9c36f2,Staten Island,NY,US,0,"{'x': -74.143937, 'y': 40.638347}",0,0,6,Richmond Terrace,0,NaN,Richmond Ter,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530796026372,2018-07-05T09:07:06.372000
17,17,96145419-0122-31e1-b7ff-26baef289215,Bayonne,NJ,US,0,"{'x': -74.098521, 'y': 40.677798}",0,0,6,NJTA - Exit 14A Improvement Project,0,NaN,Peninsula Rd,ROAD_CLOSED_EVENT,ROAD_CLOSED,1530535472114,2018-07-02T08:44:32.114000
18,18,e8691f20-3206-3e9c-b716-e8200d2bcbe3,Newark,NJ,US,1,"{'x': -74.14360642433168, 'y': 40.689676800252...",23,0,8,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Export St,HAZARD_ON_ROAD,WEATHERHAZARD,1528256917000,2018-06-05T23:48:37
19,19,cd86c6b0-2e8b-3255-a61f-cf8a5b71787f,Newark,NJ,US,1,"{'x': -74.14247989654542, 'y': 40.69214984282199}",114,0,8,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Marsh St,HAZARD_ON_ROAD,WEATHERHAZARD,1528254523000,2018-06-05T23:08:43
20,20,26831d3f-cded-3bf2-8113-c637324979aa,Newark,NJ,US,0,"{'x': -74.14372444152833, 'y': 40.6898964491942}",115,0,7,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Tyler St,HAZARD_ON_ROAD,WEATHERHAZARD,1528283661000,2018-06-06T07:14:21
21,21,3ef41850-dbe3-3061-bf7c-efb580211ed6,Newark,NJ,US,0,"{'x': -74.14178252220155, 'y': 40.69170242415773}",145,0,6,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Marsh St,HAZARD_ON_ROAD_OBJECT,WEATHERHAZARD,1528254553000,2018-06-05T23:09:13
22,22,9ad07496-4b4f-3170-abdc-f7aefbaa5c5b,NaN,NaN,US,1,"{'x': -74.1502368450165, 'y': 40.69236134878111}",0,0,8,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,NaN,NaN,HAZARD_ON_ROAD,WEATHERHAZARD,1528284910000,2018-06-06T07:35:10
23,23,c14f9617-a9fc-3093-81ac-f5d339ee6929,Newark,NJ,US,0,"{'x': -74.14319872856142, 'y': 40.690368285214...",204,0,7,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Export St,HAZARD_ON_ROAD,WEATHERHAZARD,1528255362000,2018-06-05T23:22:42
24,24,58ca7d83-4a56-34cf-a0e4-3e2f8ac39d79,Newark,NJ,US,0,"{'x': -74.14714694023134, 'y': 40.691344487063...",203,0,6,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Coastwise St,HAZARD_ON_ROAD,WEATHERHAZARD,1528284686000,2018-06-06T07:31:26
25,25,e5643f92-d6f2-3f18-b6ad-d7f503277b4c,Newark,NJ,US,0,"{'x': -74.14690017700197, 'y': 40.69178377322925}",203,0,7,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Coastwise St,HAZARD_ON_ROAD,WEATHERHAZARD,1528284551000,2018-06-06T07:29:11
26,26,43e37d75-2e75-3d57-8736-630f4501893e,Bayonne,NJ,US,0,"{'x': -74.096443, 'y': 40.678433}",0,0,7,NJTA - Exit 14A Improvement Project,0,NaN,Chosin Few Way,ROAD_CLOSED_EVENT,ROAD_CLOSED,1528289256719,2018-06-06T08:47:36.719000
27,27,4a737617-8dc6-3959-9765-10c167ef3c62,Brooklyn,NY,US,0,"{'x': -74.030699, 'y': 40.612993}",33,0,5,NaN,3,4.0,Exit 3: I-278 W / Verrazano Br / Staten Island,NaN,JAM,1530846085000,2018-07-05T23:01:25
28,28,aff059cb-ffa1-31d1-82b0-01110ad6fe97,Brooklyn,NY,US,0,"{'x': -74.030812, 'y': 40.612847}",29,0,5,NaN,2,4.0,Exit 3: I-278 W / Verrazano Br / Staten Island,HAZARD_ON_ROAD_CAR_STOPPED,WEATHERHAZARD,1530846601449,2018-07-05T23:10:01.449000
29,29,4846ac92-26b3-3421-a2da-52ab52413a25,Newark,NJ,US,0,"{'x': -74.1411066055298, 'y': 40.693524619555234}",23,0,6,Railroad Crossing: Do Not Turn Onto Tracks - P...,0,1.0,Export St,HAZARD_ON_ROAD,WEATHERHAZARD,1528254479000,2018-06-05T23:07:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61397,268,a6aa309a-f837-3d96-97e3-9aa8938d1227,Queens,NY,US,0,"{'x': -73.874297, 'y': 40.73098}",248,0,5,NaN,4,3.0,I-495 W / Qns-Midtown Expwy,JAM_HEAVY_TRAFFIC,JAM,1536631574900,2018-09-10T22:06:14.900000
61398,269,7597e3ba-fb14-3e65-91f5-8eaec4aae061,Queens,NY,US,0,"{'x': -73.846681, 'y': 40.7079}",87,0,6,NaN,4,3.0,Jackie Robinson Pkwy E,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536631640641,2018-09-10T22:07:20.641000
61399,270,fdbd7f9f-c018-3c3e-81ee-58b08e1ee9d4,Queens,NY,US,0,"{'x': -73.843779, 'y': 40.708129}",74,0,5,NaN,1,3.0,Jackie Robinson Pkwy E,ACCIDENT_MINOR,ACCIDENT,1536631674093,2018-09-10T22:07:54.093000
61400,271,3ac06ed7-21fe-3edb-a36a-ef176342796f,Queens,NY,US,1,"{'x': -73.883626, 'y': 40.728416}",83,0,7,NaN,2,3.0,I-495 E / Qns-Midtown Expwy,JAM_HEAVY_TRAFFIC,JAM,1536631920710,2018-09-10T22:12:00.710000
61401,272,e308d75e-320c-3ed5-b885-3c83dd8069df,Queens,NY,US,1,"{'x': -73.877932, 'y': 40.729611}",62,0,7,NaN,2,3.0,I-495 E / Qns-Midtown Expwy,ACCIDENT_MINOR,ACCIDENT,1536631966671,2018-09-10T22:12:46.671000
61402,273,f46117ee-236b-3553-9bf6-a31d822f8b9e,Queens,NY,US,0,"{'x': -73.839242, 'y': 40.728109}",154,0,5,NaN,3,3.0,Grand Central Pkwy E,JAM_HEAVY_TRAFFIC,JAM,1536632767283,2018-09-10T22:26:07.283000
61403,274,75713746-252d-3c55-ac1c-5602e3deadc7,Queens,NY,US,5,"{'x': -73.838172, 'y': 40.726241}",159,0,10,NaN,2,3.0,Grand Central Pkwy E,ACCIDENT_MINOR,ACCIDENT,1536625837695,2018-09-10T20:30:37.695000
61404,275,28cd0d5d-f38c-3a56-84e3-04376f9ba6c2,Queens,NY,US,5,"{'x': -73.879109, 'y': 40.729182}",65,0,10,NaN,2,3.0,I-495 E / Qns-Midtown Expwy,HAZARD_ON_ROAD_CAR_STOPPED,WEATHERHAZARD,1536630303362,2018-09-10T21:45:03.362000
61405,276,2d2d9c55-d2e7-361b-87cd-0450ae2bcbd4,Queens,NY,US,3,"{'x': -73.911567, 'y': 40.769367}",279,0,10,NaN,4,3.0,I-278 E / Grand Central Pkwy,HAZARD_ON_ROAD_CAR_STOPPED,WEATHERHAZARD,1536629051233,2018-09-10T21:24:11.233000
61406,277,e4471151-214f-310f-8d4d-1f85e561c9a1,Queens,NY,US,0,"{'x': -73.844439, 'y': 40.740552}",238,0,5,NaN,5,3.0,I-495 W / Long Island Expwy,NaN,JAM,1536632860935,2018-09-10T22:27:40.935000
61407,278,ededb7be-add9-3bd2-a52e-3e6671d17933,Queens,NY,US,0,"{'x': -73.752707, 'y': 40.727915}",239,0,6,NaN,2,3.0,Grand Central Pkwy W,NaN,JAM,1536632072215,2018-09-10T22:14:32.215000
61408,279,00a876a4-4ae3-3d42-9497-dfd92c04c9ea,North Hills,NY,US,0,"{'x': -73.693994, 'y': 40.767787}",251,0,5,NaN,5,3.0,I-495 W,NaN,JAM,1536632204848,2018-09-10T22:16:44.848000
61409,280,4542bd73-0f22-36d2-9e80-9949b8c61480,NaN,NaN,US,5,"{'x': -73.671419, 'y': 40.683042}",271,0,10,NaN,2,3.0,Southern State Pkwy W,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536628232814,2018-09-10T21:10:32.814000
61410,281,e95a2104-8fd5-3da4-9a9f-0c75d488d793,Queens,NY,US,0,"{'x': -73.777133, 'y': 40.72257}",226,0,7,NaN,4,3.0,Grand Central Pkwy W,NaN,WEATHERHAZARD,1536631728910,2018-09-10T22:08:48.910000
61411,282,258f82d4-2c25-33f3-b204-9be9f97e357a,Queens,NY,US,0,"{'x': -73.789451, 'y': 40.740053}",70,0,6,NaN,3,3.0,I-495 E / Long Island Expwy,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536632252267,2018-09-10T22:17:32.267000
61412,283,f99db748-78b0-3eaa-92c2-32708ff0803d,Queens,NY,US,0,"{'x': -73.826015, 'y': 40.779705}",22,0,8,NaN,5,3.0,I-678 N / Whitestone Expwy,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536631805277,2018-09-10T22:10:05.277000
61413,284,65810b35-7ac3-331a-96e7-39529c7800cb,Queens,NY,US,1,"{'x': -73.778768, 'y': 40.721373}",235,0,7,NaN,4,3.0,Grand Central Pkwy W,NaN,ACCIDENT,1536631807832,2018-09-10T22:10:07.832000
61414,285,96e3353f-4b8a-3a7d-aa0c-1f0f93e1c2a2,Queens,NY,US,0,"{'x': -73.818071, 'y': 40.705758}",155,0,5,NaN,1,3.0,I-678 S / Van Wyck Expwy,JAM_HEAVY_TRAFFIC,JAM,1536631248392,2018-09-10T22:00:48.392000
61415,286,be2e1d3f-0c11-3d9d-bda3-33b6ec82da19,Queens,NY,US,0,"{'x': -73.809705, 'y': 40.69012}",156,0,5,NaN,1,3.0,I-678 S / Van Wyck Expwy,JAM_MODERATE_TRAFFIC,JAM,1536631341791,2018-09-10T22:02:21.791000
61416,287,cf407d54-0c36-3cc1-b0b9-2f76c381d4ed,Queens,NY,US,0,"{'x': -73.807392, 'y': 40.685987}",156,0,5,NaN,1,3.0,I-678 S / Van Wyck Expwy,JAM_HEAVY_TRAFFIC,JAM,1536631366905,2018-09-10T22:02:46.905000
61417,288,891f82b6-a67c-38bb-bd6c-f5df8152dae9,Queens,NY,US,0,"{'x': -73.801257, 'y': 40.670743}",178,0,5,NaN,1,3.0,I-678 S / Van Wyck Expwy,JAM_MODERATE_TRAFFIC,JAM,1536631463575,2018-09-10T22:04:23.575000
61418,289,cd2a7b57-a385-33b2-9d31-12348b9aae29,Lake Success,NY,US,1,"{'x': -73.721631, 'y': 40.764597}",262,0,8,NaN,3,3.0,I-495 W,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536632325352,2018-09-10T22:18:45.352000
61419,290,c5d034d3-b7cd-3459-b927-7f546a660773,Queens,NY,US,0,"{'x': -73.725315, 'y': 40.764045}",255,0,5,NaN,5,3.0,I-495 W / Long Island Expwy,NaN,JAM,1536632331526,2018-09-10T22:18:51.526000
61420,291,af010e8c-3e60-3acd-914a-cecea5ec3639,Queens,NY,US,0,"{'x': -73.74623, 'y': 40.752586}",231,0,5,NaN,5,3.0,I-495 W / Long Island Expwy,NaN,JAM,1536632437527,2018-09-10T22:20:37.527000
61421,292,336264e3-68cb-3482-b448-b09ecad1667e,Queens,NY,US,0,"{'x': -73.752869, 'y': 40.727839}",239,0,5,NaN,3,3.0,Grand Central Pkwy W,HAZARD_ON_ROAD_CONSTRUCTION,WEATHERHAZARD,1536632529154,2018-09-10T22:22:09.154000
61422,293,d93eaca4-dd5a-3775-9bf1-079445ff8e97,Bronx,NY,US,0,"{'x': -73.873686, 'y': 40.836829}",195,0,5,NaN,2,3.0,Bronx River Pkwy S,HAZARD_ON_ROAD_CAR_STOPPED,WEATHERHAZARD,1536632836279,2018-09-10T22:27:16.279000
61423,294,95dbb982-485c-32ea-b7eb-97605556dca3,Manhattan,NY,US,1,"{'x': -73.96561, 'y': 40.813164}",211,0,9,NaN,3,3.0,Henry Hudson Pkwy S,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536631645251,2018-09-10T22:07:25.251000
61424,295,56a6ec36-3886-3878-b6c3-8b963a01322b,Bronx,NY,US,0,"{'x': -73.923953, 'y': 40.849106}",214,0,5,NaN,2,3.0,I-87 S / Major Deegan Expwy,JAM_HEAVY_TRAFFIC,JAM,1536631815772,2018-09-10T22:10:15.772000
61425,296,d2d595e4-3e5b-3813-966c-d95e1c8f039e,Bronx,NY,US,0,"{'x': -73.86931, 'y': 40.880138}",15,0,6,NaN,2,3.0,Bronx River Pkwy N,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536630829209,2018-09-10T21:53:49.209000
61426,297,add734c9-df0e-3b57-b2ee-a4cab6dcee36,Queens,NY,US,0,"{'x': -73.823086, 'y': 40.788269}",26,0,5,NaN,4,3.0,I-678 N / Whitestone Expwy,HAZARD_ON_SHOULDER_CAR_STOPPED,WEATHERHAZARD,1536632154904,2018-09-10T22:15:54.904000

In [4]:
irr

,Unnamed: 0,id,alerts,alerts_count,cause_alert,cause_type,city,state,country,delay_seconds,...,regular_speed,seconds,severity,speed,street,trend,type,update_date,update_date_millis,update_utc_date
0,0,62466158,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Ma...",5,"{'country': 'US', 'nThumbsUp': 27, 'city': 'Ma...",ACCIDENT,Manhattan,NY,US,375,...,63.64,442,1,10.83,FDR Dr N,-1,Small,Fri Jul 6 03:17:43 +0000 2018,1530847063093,2018-07-05T23:17:43.093000
1,1,63205871,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",2,"{'country': 'US', 'nThumbsUp': 9, 'city': 'Bro...",ACCIDENT,Brooklyn,NY,US,682,...,30.58,763,2,8.71,I-278 E / Kosciuszko Br,-1,Medium,Fri Jul 6 03:17:43 +0000 2018,1530847063062,2018-07-05T23:17:43.062000
2,2,62726115,"[{'country': 'US', 'nThumbsUp': 6, 'city': 'Je...",3,NaN,NaN,Jersey City,NJ,US,361,...,100.00,420,2,12.62,Pulaski Skwy N,0,Small,Fri Jul 6 03:17:43 +0000 2018,1530847063094,2018-07-05T23:17:43.094000
3,3,62886114,[],0,NaN,NaN,Manhattan,NY,US,356,...,10.37,614,0,4.81,W 46th St,-1,Small,Fri Jul 6 03:17:43 +0000 2018,1530847063093,2018-07-05T23:17:43.093000
4,4,62606116,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Ma...",3,NaN,WEATHERHAZARD,Manhattan,NY,US,347,...,21.19,409,1,9.56,FDR Dr N,1,Small,Fri Jul 6 03:17:43 +0000 2018,1530847063073,2018-07-05T23:17:43.073000
5,5,62465958,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Br...",4,NaN,NaN,Bronx,NY,US,1554,...,68.63,1714,3,7.97,I-87 N / Major Deegan Expwy,1,Large,Fri Jul 6 03:17:43 +0000 2018,1530847063076,2018-07-05T23:17:43.076000
6,6,62885814,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",3,"{'country': 'US', 'nThumbsUp': 16, 'city': 'Br...",ACCIDENT,Bronx,NY,US,158,...,68.12,239,1,27.24,I-95 N / Cross Bronx Expwy,-1,Small,Fri Jul 6 03:17:43 +0000 2018,1530847063072,2018-07-05T23:17:43.072000
7,0,63661386,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",1,NaN,NaN,Queens,NY,US,916,...,11.50,1149,1,2.72,31st Ave,0,Large,Sun Jul 29 18:53:50 +0000 2018,1532890430257,2018-07-29T14:53:50.257000
8,1,64141962,[],0,NaN,NaN,Queens,NY,US,635,...,12.56,812,1,5.05,31st St,0,Medium,Sun Jul 29 18:53:50 +0000 2018,1532890430181,2018-07-29T14:53:50.181000
9,2,64141782,[],0,NaN,NaN,Queens,NY,US,565,...,13.75,804,1,5.10,31st St,0,Medium,Sun Jul 29 18:53:50 +0000 2018,1532890430266,2018-07-29T14:53:50.266000
10,3,63580827,[],0,NaN,NaN,Weehawken,NJ,US,336,...,19.58,410,1,10.18,SR-495 E,-1,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430253,2018-07-29T14:53:50.253000
11,4,63661476,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'St...",4,NaN,NaN,Staten Island,NY,US,268,...,52.33,358,2,21.07,I-278 E / Verrazano Br / Upper Level,0,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430258,2018-07-29T14:53:50.258000
12,5,63401739,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Je...",1,NaN,NaN,Jersey City,NJ,US,1451,...,19.92,1546,2,3.31,SR-139 E (lower),-1,Large,Sun Jul 29 18:53:50 +0000 2018,1532890430204,2018-07-29T14:53:50.204000
13,6,63401849,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",1,NaN,NaN,Brooklyn,NY,US,328,...,15.23,463,1,8.45,Surf Ave,1,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430192,2018-07-29T14:53:50.192000
14,7,63781495,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Je...",1,NaN,NaN,Jersey City,NJ,US,853,...,31.94,957,2,6.56,I-78 E / NJ Turnpike,1,Large,Sun Jul 29 18:53:50 +0000 2018,1532890430245,2018-07-29T14:53:50.245000
15,8,63781975,[],0,NaN,NaN,Manhattan,NY,US,472,...,11.47,666,1,3.68,E 36th St,-1,Medium,Sun Jul 29 18:53:50 +0000 2018,1532890430272,2018-07-29T14:53:50.272000
16,9,63521818,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Ma...",1,NaN,NaN,Manhattan,NY,US,189,...,10.88,361,0,8.54,W 23rd St,-1,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430224,2018-07-29T14:53:50.224000
17,10,63401819,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Ma...",3,NaN,NaN,Manhattan,NY,US,1594,...,7.20,1699,2,1.47,Broome St,0,Medium,Sun Jul 29 18:53:50 +0000 2018,1532890430227,2018-07-29T14:53:50.227000
18,11,63781825,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",6,NaN,NaN,Brooklyn,NY,US,580,...,39.40,895,2,25.82,I-278 W / Bklyn-Qns Expwy,-1,Small,Sun Jul 29 18:53:55 +0000 2018,1532890435623,2018-07-29T14:53:55.623000
19,12,64522000,[],0,NaN,NaN,Queens,NY,US,509,...,14.31,672,1,3.32,28th Ave,1,Medium,Sun Jul 29 18:53:53 +0000 2018,1532890433819,2018-07-29T14:53:53.819000
20,13,64261981,[],0,NaN,NaN,Queens,NY,US,160,...,9.80,308,0,6.53,Roosevelt Ave,0,Small,Sun Jul 29 18:53:53 +0000 2018,1532890433759,2018-07-29T14:53:53.759000
21,14,63941574,[],0,NaN,NaN,Jersey City,NJ,US,1561,...,9.96,1775,2,2.66,Marin Blvd,-1,Medium,Sun Jul 29 18:53:50 +0000 2018,1532890430233,2018-07-29T14:53:50.233000
22,15,63662006,[],0,NaN,NaN,Queens,NY,US,483,...,14.05,675,1,4.83,Roosevelt Ave,1,Medium,Sun Jul 29 18:53:54 +0000 2018,1532890434477,2018-07-29T14:53:54.477000
23,16,64260321,[],0,NaN,NaN,Queens,NY,US,966,...,11.15,1176,1,2.17,31st Ave,0,Large,Sun Jul 29 18:53:50 +0000 2018,1532890430198,2018-07-29T14:53:50.198000
24,17,63781625,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'No...",1,NaN,NaN,North New Hyde Park,NY,US,718,...,71.06,822,3,12.46,Northern State Pkwy E,0,Medium,Sun Jul 29 18:53:53 +0000 2018,1532890433745,2018-07-29T14:53:53.745000
25,18,63521628,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Qu...",7,NaN,NaN,Queens,NY,US,1143,...,25.28,1457,3,19.96,I-495 E / Long Island Expwy,1,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430243,2018-07-29T14:53:50.243000
26,19,63580407,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",1,NaN,NaN,Queens,NY,US,508,...,23.10,604,2,9.58,Rockaway Blvd,0,Small,Sun Jul 29 18:53:52 +0000 2018,1532890432999,2018-07-29T14:53:52.999000
27,20,64521730,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",4,NaN,NaN,Queens,NY,US,918,...,30.89,1193,3,21.28,Cross Island Pkwy S,0,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430215,2018-07-29T14:53:50.215000
28,21,63981753,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",4,NaN,NaN,Bronx,NY,US,269,...,34.60,430,1,27.87,I-87 N / Major Deegan Expwy,-1,Small,Sun Jul 29 18:53:50 +0000 2018,1532890430174,2018-07-29T14:53:50.174000
29,22,63941954,[],0,NaN,NaN,Bronx,NY,US,859,...,27.72,1100,1,4.86,Grand Concourse (Service Rd),0,Large,Sun Jul 29 18:53:50 +0000 2018,1532890430212,2018-07-29T14:53:50.212000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,22,65620595,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",1,NaN,NaN,Queens,NY,US,685,...,69.00,733,2,4.42,to Grand Central Pkwy W / RFK Br,-1,Medium,Tue Sep 4 11:25:06 +0000 2018,1536060306066,2018-09-04T07:25:06.066000
2170,23,65620665,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'St...",3,NaN,NaN,Staten Island,NY,US,476,...,36.63,530,1,4.28,Steuben St,0,Medium,Tue Sep 4 11:25:05 +0000 2018,1536060305947,2018-09-04T07:25:05.947000
2171,24,65780184,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Fo...",1,NaN,NaN,Fort Lee,NJ,US,424,...,50.46,468,2,7.18,SR-4 E,1,Small,Tue Sep 4 11:25:06 +0000 2018,1536060306075,2018-09-04T07:25:06.075000
2172,25,65480406,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Fo...",2,NaN,NaN,Fort Lee,NJ,US,877,...,11.53,978,2,4.84,to I-95 N / Upper Level,1,Small,Tue Sep 4 11:25:06 +0000 2018,1536060306004,2018-09-04T07:25:06.004000
2173,26,65200259,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'En...",4,NaN,NaN,Englewood,NJ,US,279,...,91.27,331,2,13.23,SR-4 E,-1,Small,Tue Sep 4 11:25:06 +0000 2018,1536060306004,2018-09-04T07:25:06.004000
2174,27,66020422,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Fo...",2,NaN,NaN,Fort Lee,NJ,US,521,...,43.94,571,2,5.99,Bergen Blvd,0,Medium,Tue Sep 4 11:25:06 +0000 2018,1536060306006,2018-09-04T07:25:06.006000
2175,0,66208442,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",10,NaN,WEATHERHAZARD,Queens,NY,US,339,...,83.31,444,3,20.57,Grand Central Pkwy W,1,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178624,2018-09-10T16:09:38.624000
2176,1,65550658,[],0,NaN,NaN,Queens,NY,US,544,...,9.90,689,1,4.76,Fresh Pond Rd,-1,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178729,2018-09-10T16:09:38.729000
2177,2,66591090,[],0,NaN,NaN,Jersey City,NJ,US,611,...,19.71,755,1,5.40,W Side Ave,0,Medium,Mon Sep 10 20:09:38 +0000 2018,1536610178607,2018-09-10T16:09:38.607000
2178,3,65991154,[],0,NaN,NaN,North Bergen,NJ,US,461,...,19.05,530,1,3.74,Union Tpk,1,Medium,Mon Sep 10 20:09:43 +0000 2018,1536610183355,2018-09-10T16:09:43.355000
2179,4,66590760,[],0,NaN,NaN,Brooklyn,NY,US,721,...,5.57,852,1,2.72,Union St,-1,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178603,2018-09-10T16:09:38.603000
2180,5,65611107,[],0,NaN,NaN,Manhattan,NY,US,710,...,8.51,832,1,2.32,Spring St,0,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178672,2018-09-10T16:09:38.672000
2181,6,66330521,[],0,NaN,NaN,Manhattan,NY,US,663,...,16.88,748,1,2.96,Broadway,-1,Medium,Mon Sep 10 20:09:38 +0000 2018,1536610178634,2018-09-10T16:09:38.634000
2182,7,65691116,[],0,NaN,NaN,Queens,NY,US,832,...,13.43,1003,1,3.17,Kissena Blvd,1,Large,Mon Sep 10 20:09:38 +0000 2018,1536610178620,2018-09-10T16:09:38.620000
2183,8,65611007,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",1,NaN,NaN,Queens,NY,US,575,...,24.30,612,2,3.97,to I-678 S / Van Wyck Expwy,0,Medium,Mon Sep 10 20:09:38 +0000 2018,1536610178685,2018-09-10T16:09:38.685000
2184,9,65610667,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Je...",4,NaN,NaN,Jersey City,NJ,US,995,...,27.81,1139,2,7.22,SR-440 N,1,Large,Mon Sep 10 20:09:38 +0000 2018,1536610178631,2018-09-10T16:09:38.631000
2185,10,65409589,[],0,NaN,NaN,Ridgefield,NJ,US,383,...,36.17,449,1,8.18,Broad Ave,0,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178734,2018-09-10T16:09:38.734000
2186,11,65830895,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Ma...",3,NaN,WEATHERHAZARD,Manhattan,NY,US,490,...,22.42,591,2,12.75,I-95 N / Upper Level,1,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178665,2018-09-10T16:09:38.665000
2187,12,66590870,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",2,NaN,WEATHERHAZARD,Bronx,NY,US,599,...,73.81,707,2,11.55,I-87 S / Major Deegan Expwy,1,Medium,Mon Sep 10 20:09:38 +0000 2018,1536610178631,2018-09-10T16:09:38.631000
2188,13,65831085,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Br...",11,NaN,NaN,Bronx,NY,US,595,...,42.07,786,2,20.11,Bronx River Pkwy S,0,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178628,2018-09-10T16:09:38.628000
2189,14,66050583,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Br...",6,"{'country': 'US', 'nThumbsUp': 7, 'city': 'Bro...",ACCIDENT,Bronx,NY,US,1161,...,17.88,1315,3,9.40,I-95 N / Cross Bronx Expwy,0,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178630,2018-09-10T16:09:38.630000
2190,15,65610727,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Ma...",2,NaN,NaN,Manhattan,NY,US,734,...,20.09,823,2,6.80,Harlem River Dr S,-1,Small,Mon Sep 10 20:09:43 +0000 2018,1536610183693,2018-09-10T16:09:43.693000
2191,16,65830925,"[{'country': 'US', 'nThumbsUp': 2, 'city': 'Ed...",5,NaN,WEATHERHAZARD,Edgewater,NJ,US,958,...,37.17,1131,2,7.52,River Rd,1,Large,Mon Sep 10 20:09:41 +0000 2018,1536610181124,2018-09-10T16:09:41.124000
2192,17,66591110,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Ma...",2,NaN,NaN,Manhattan,NY,US,561,...,7.07,820,1,3.68,E 125th St,-1,Small,Mon Sep 10 20:09:38 +0000 2018,1536610178682,2018-09-10T16:09:38.682000
2193,18,66331051,[],0,NaN,NaN,North Bergen,NJ,US,1183,...,17.65,1335,1,2.16,51st St,0,Large,Mon Sep 10 20:09:38 +0000 2018,1536610178726,2018-09-10T16:09:38.726000
2194,0,65414999,[],0,NaN,NaN,Manhattan,NY,US,339,...,15.33,582,0,5.94,E 59th St,0,Small,Tue Sep 11 02:27:02 +0000 2018,1536632822547,2018-09-10T22:27:02.547000
2195,1,66215002,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",1,NaN,NaN,Queens,NY,US,550,...,58.30,613,2,5.86,I-495 W / Qns-Midtown Tun / HOV,0,Medium,Tue Sep 11 02:27:02 +0000 2018,1536632822545,2018-09-10T22:27:02.545000
2196,2,66055003,"[{'country': 'US', 'nThumbsUp': 1, 'city': 'Qu...",3,NaN,NaN,Queens,NY,US,470,...,62.82,513,1,5.58,I-495 W / Qns-Midtown Tun,0,Medium,Tue Sep 11 02:27:02 +0000 2018,1536632822549,2018-09-10T22:27:02.549000
2197,3,65414809,"[{'country': 'US', 'nThumbsUp': 0, 'city': 'Qu...",5,"{'country': 'US', 'nThumbsUp': 1, 'city': 'Que...",ACCIDENT,Queens,NY,US,119,...,82.74,188,1,31.59,I-495 E / Qns-Midtown Expwy,1,Small,Tue Sep 11 02:27:02 +0000 2018,1536632822547,2018-09-10T22:27:02.547000
2198,4,65615007,[],0,NaN,NaN,Queens,NY,US,612,...,18.07,722,1,2.62,88th Ave,1,Medium,Tue Sep 11 02:27:04 +0000 2018,1536632824183,2018-09-10T22:27:04.183000

In [5]:
jm

,Unnamed: 0,uuid,blocking_alert_uuid,city,state,country,delay,start_node,end_node,length,...,line,road_type,street,segments,speed,speed_KMH,turn_type,type,pub_millis,pub_utc_date
0,0,1091249488,NaN,Perth Amboy,NJ,US,169,NaN,NY-440 N / Outerbridge Crossing,2081,...,"[{'x': -74.270613, 'y': 40.526598}, {'x': -74....",3,SR-440 N / Outerbridge Crossing,[{}],8.244444,29.68,NONE,NONE,1530846630171,2018-07-05T23:10:30.171000
1,1,1095145876,NaN,Staten Island,NY,US,116,NaN,NY-440 N,835,...,"[{'x': -74.246496, 'y': 40.524784}, {'x': -74....",3,NY-440 N / Outerbridge Crossing,[{}],5.458333,19.65,NONE,NONE,1530846845855,2018-07-05T23:14:05.855000
2,2,1050403853,32d535c5-4015-3ec2-b8e9-3770525c2540,Elizabeth,NJ,US,-1,NaN,NaN,265,...,"[{'x': -74.189449, 'y': 40.681968}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774199119,2018-07-05T03:03:19.119000
3,3,1014506920,e8f2eb2a-cfb1-314e-9b06-6bf215b77139,Elizabeth,NJ,US,-1,NaN,Earhart Dr,150,...,"[{'x': -74.191085, 'y': 40.681085}, {'x': -74....",1,Basilone Rd,[{}],0.000000,0.00,NONE,NONE,1530687778462,2018-07-04T03:02:58.462000
4,4,936779831,ca3381b7-0941-3146-9462-f68debddf4c6,Elizabeth,NJ,US,-1,NaN,Earhart Dr,374,...,"[{'x': -74.188656, 'y': 40.685938}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530535612023,2018-07-02T08:46:52.023000
5,5,1070660215,1ece3af1-d4c0-3399-a0b6-c05e1adb55a4,Elizabeth,NJ,US,-1,NaN,NaN,90,...,"[{'x': -74.189309, 'y': 40.681168}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774197381,2018-07-05T03:03:17.381000
6,6,1061763046,37069b8a-975a-3dd9-adf2-38b5165344fd,Elizabeth,NJ,US,-1,NaN,NaN,65,...,"[{'x': -74.189072, 'y': 40.684863}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198770,2018-07-05T03:03:18.770000
7,7,1054503000,2d32afd9-0436-3169-9c3c-8d55da7e41c5,Elizabeth,NJ,US,-1,NaN,NaN,60,...,"[{'x': -74.189206, 'y': 40.684333}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198756,2018-07-05T03:03:18.756000
8,8,1053843031,3f89ff35-196a-3ac5-ba2d-1ae19a2b7af9,Elizabeth,NJ,US,-1,NaN,NaN,50,...,"[{'x': -74.188875, 'y': 40.685426}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198764,2018-07-05T03:03:18.764000
9,9,1089266549,NaN,Elizabeth,NJ,US,82,NaN,Basilone Rd,695,...,"[{'x': -74.186058, 'y': 40.675433}, {'x': -74....",1,Earhart Dr,"[{}, {}, {}, {}]",4.625000,16.65,NONE,NONE,1530847058712,2018-07-05T23:17:38.712000
10,10,1089093139,NaN,Brooklyn,NY,US,94,NaN,W 36th St,385,...,"[{'x': -73.998043, 'y': 40.578596}, {'x': -73....",1,Bayview Ave,[{}],2.902778,10.45,NONE,NONE,1530846486099,2018-07-05T23:08:06.099000
11,11,1095083256,NaN,Brooklyn,NY,US,134,NaN,Brighton 4th St,235,...,"[{'x': -73.967344, 'y': 40.580421}, {'x': -73....",6,Neptune Ave,"[{}, {}, {}, {}]",1.325000,4.77,NONE,NONE,1530846625983,2018-07-05T23:10:25.983000
12,12,1091297778,NaN,Brooklyn,NY,US,90,NaN,Coney Island Ave,327,...,"[{'x': -73.96685, 'y': 40.597683}, {'x': -73.9...",6,Ave U,"[{}, {}, {}, {}, {}]",1.877778,6.76,NONE,NONE,1530846773790,2018-07-05T23:12:53.790000
13,13,1104143605,NaN,Brooklyn,NY,US,146,NaN,Ave U,253,...,"[{'x': -73.970056, 'y': 40.599632}, {'x': -73....",1,E 2nd St,[{}],1.338889,4.82,NONE,NONE,1530846777636,2018-07-05T23:12:57.636000
14,14,1095504144,NaN,Queens,NY,US,92,NaN,Rockaway Beach Blvd,201,...,"[{'x': -73.844005, 'y': 40.579516}, {'x': -73....",1,Beach 123rd St,[{}],1.588889,5.72,NONE,NONE,1530846778406,2018-07-05T23:12:58.406000
15,15,1083873923,NaN,Brooklyn,NY,US,68,NaN,Neptune Ave,215,...,"[{'x': -73.957635, 'y': 40.584457}, {'x': -73....",1,E 12th St,"[{}, {}, {}, {}]",1.466667,5.28,NONE,NONE,1530846916953,2018-07-05T23:15:16.953000
16,16,1091359418,NaN,Brooklyn,NY,US,80,NaN,18th Ave,475,...,"[{'x': -73.994847, 'y': 40.604437}, {'x': -73....",1,84th St,"[{}, {}, {}]",2.397222,8.63,NONE,NONE,1530846986866,2018-07-05T23:16:26.866000
17,17,1085620242,NaN,Brooklyn,NY,US,166,NaN,Ave Y,163,...,"[{'x': -73.952581, 'y': 40.58884}, {'x': -73.9...",1,E 17th St,[{}],0.858333,3.09,NONE,NONE,1530846987701,2018-07-05T23:16:27.701000
18,18,1104206385,NaN,Brooklyn,NY,US,100,NaN,Bay 41st St,394,...,"[{'x': -73.989393, 'y': 40.599257}, {'x': -73....",6,86th St,"[{}, {}, {}, {}, {}, {}, {}]",2.563889,9.23,NONE,NONE,1530847058529,2018-07-05T23:17:38.529000
19,19,1083749623,NaN,Brooklyn,NY,US,87,NaN,Cropsey Ave,175,...,"[{'x': -73.998749, 'y': 40.59952}, {'x': -74.0...",1,Bay 28th St,[{}],1.336111,4.81,NONE,NONE,1530846483353,2018-07-05T23:08:03.353000
20,20,1082466902,4efd8189-c26f-30c7-895d-ea43b2c144d6,Bayonne,NJ,US,-1,NaN,NaN,887,...,"[{'x': -74.143173, 'y': 40.639001}, {'x': -74....",3,Bayonne Br N,[{}],0.000000,0.00,NONE,NONE,1530838823113,2018-07-05T21:00:23.113000
21,21,1080769533,00a2486c-467a-3682-9726-c9a874ebff2a,Staten Island,NY,US,-1,NaN,NaN,67,...,"[{'x': -74.143276, 'y': 40.638685}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827240,2018-07-05T21:00:27.240000
22,22,1088789607,062b2fd0-ded3-3840-8560-7df4c651c13b,Bayonne,NJ,US,-1,NaN,NY-440 S / Bayonne Br,890,...,"[{'x': -74.140179, 'y': 40.646674}, {'x': -74....",3,Bayonne Br S,[{}],0.000000,0.00,NONE,NONE,1530838827671,2018-07-05T21:00:27.671000
23,23,1086109869,46853519-cd7d-3eec-9e5e-86c75f9c36f2,Staten Island,NY,US,-1,NaN,Newark Ave,67,...,"[{'x': -74.143937, 'y': 40.638347}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827733,2018-07-05T21:00:27.733000
24,24,1084229941,8cbd6c2d-ce08-3936-b68a-5268a88afd75,Staten Island,NY,US,-1,NaN,Morningstar Rd,87,...,"[{'x': -74.143937, 'y': 40.638347}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827754,2018-07-05T21:00:27.754000
25,25,1082470022,67b17a92-962e-37d9-a4b2-3bea62ae43ae,Staten Island,NY,US,-1,NaN,NaN,87,...,"[{'x': -74.144805, 'y': 40.637932}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827754,2018-07-05T21:00:27.754000
26,26,1095560284,NaN,Staten Island,NY,US,100,NaN,Ocean Ter,725,...,"[{'x': -74.121119, 'y': 40.608338}, {'x': -74....",6,Manor Rd,"[{}, {}, {}, {}, {}, {}, {}, {}, {}]",4.150000,14.94,NONE,NONE,1530846987831,2018-07-05T23:16:27.831000
27,27,941723366,43e37d75-2e75-3d57-8736-630f4501893e,Bayonne,NJ,US,-1,NaN,NaN,173,...,"[{'x': -74.096443, 'y': 40.678433}, {'x': -74....",6,Chosin Few Way,[{}],0.000000,0.00,NONE,NONE,1530528932157,2018-07-02T06:55:32.157000
28,28,1054502550,96145419-0122-31e1-b7ff-26baef289215,Bayonne,NJ,US,-1,NaN,Chosin Few Way,189,...,"[{'x': -74.098521, 'y': 40.677798}, {'x': -74....",2,Peninsula Rd,[{}],0.000000,0.00,NONE,NONE,1530774198610,2018-07-05T03:03:18.610000
29,29,1087960840,NaN,NaN,NaN,US,95,Elizabeth,Newark,247,...,"[{'x': -74.178823, 'y': 40.689952}, {'x': -74....",1,Terminal B Arrivals,[{}],1.227778,4.42,NONE,NONE,1530846776135,2018-07-05T23:12:56.135000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82348,302,77303318,NaN,Bronx,NY,US,82,NaN,Leggett Ave,189,...,"[{'x': -73.90144, 'y': 40.812897}, {'x': -73.8...",7,Southern Blvd,[{}],1.461111,5.26,NONE,NONE,1536632675301,2018-09-10T22:24:35.301000
82349,303,70465113,NaN,Bronx,NY,US,67,NaN,E 161st St,484,...,"[{'x': -73.909874, 'y': 40.815949}, {'x': -73....",1,Cauldwell Ave,"[{}, {}]",3.255556,11.72,NONE,NONE,1536632676193,2018-09-10T22:24:36.193000
82350,304,72871672,NaN,Bronx,NY,US,67,NaN,E 149th St,371,...,"[{'x': -73.913192, 'y': 40.818003}, {'x': -73....",7,Brook Ave,"[{}, {}, {}]",2.833333,10.20,NONE,NONE,1536632746299,2018-09-10T22:25:46.299000
82351,305,64212227,NaN,Bronx,NY,US,76,NaN,Seward Ave,542,...,"[{'x': -73.868276, 'y': 40.82342}, {'x': -73.8...",1,Noble Ave,"[{}, {}, {}, {}]",2.275000,8.19,NONE,NONE,1536632746838,2018-09-10T22:25:46.838000
82352,306,77304408,NaN,Bronx,NY,US,98,NaN,Bronxdale Ave,254,...,"[{'x': -73.866996, 'y': 40.848673}, {'x': -73....",1,Cruger Ave,[{}],1.563889,5.63,NONE,NONE,1536632676050,2018-09-10T22:24:36.050000
82353,307,87965859,NaN,Bronx,NY,US,218,NaN,Jennings St,201,...,"[{'x': -73.889727, 'y': 40.834058}, {'x': -73....",6,Southern Blvd,[{}],0.794444,2.86,NONE,NONE,1536632676156,2018-09-10T22:24:36.156000
82354,308,68065815,NaN,Bronx,NY,US,65,NaN,E 188th St,590,...,"[{'x': -73.894414, 'y': 40.866037}, {'x': -73....",6,Grand Concourse,"[{}, {}, {}, {}]",4.772222,17.18,NONE,NONE,1536632676696,2018-09-10T22:24:36.696000
82355,309,64211007,NaN,Bronx,NY,US,91,NaN,W 190th St,230,...,"[{'x': -73.900596, 'y': 40.866349}, {'x': -73....",1,Grand Ave,[{}],1.677778,6.04,NONE,NONE,1536632746018,2018-09-10T22:25:46.018000
82356,310,65741686,NaN,Bronx,NY,US,104,NaN,E 169th St,555,...,"[{'x': -73.903337, 'y': 40.837641}, {'x': -73....",7,Washington Ave,"[{}, {}, {}]",3.022222,10.88,NONE,NONE,1536632817690,2018-09-10T22:26:57.690000
82357,311,72879652,NaN,Bronx,NY,US,76,NaN,Stillwell Ave,593,...,"[{'x': -73.845917, 'y': 40.857353}, {'x': -73....",2,Pelham Pkwy S (Service Rd),"[{}, {}]",2.897222,10.43,NONE,NONE,1536632817737,2018-09-10T22:26:57.737000
82358,312,70501093,NaN,Bronx,NY,US,100,NaN,Grand Concourse (Service Rd),250,...,"[{'x': -73.909174, 'y': 40.849899}, {'x': -73....",1,E 177th St,"[{}, {}]",1.463889,5.27,NONE,NONE,1536632818205,2018-09-10T22:26:58.205000
82359,313,70504003,NaN,Bronx,NY,US,78,NaN,Westchester Ave,219,...,"[{'x': -73.831132, 'y': 40.845307}, {'x': -73....",7,Crosby Ave,[{}],1.441667,5.19,NONE,NONE,1536632819685,2018-09-10T22:26:59.685000
82360,314,65697706,NaN,Bronx,NY,US,107,NaN,E 186th St,227,...,"[{'x': -73.894412, 'y': 40.855813}, {'x': -73....",1,Park Ave,"[{}, {}, {}]",1.730556,6.23,NONE,NONE,1536632605084,2018-09-10T22:23:25.084000
82361,315,63695107,NaN,Bronx,NY,US,77,NaN,Westchester Ave,286,...,"[{'x': -73.876993, 'y': 40.831514}, {'x': -73....",1,Manor Ave,[{}],1.658333,5.97,NONE,NONE,1536631390366,2018-09-10T22:03:10.366000
82362,316,68996254,NaN,Bronx,NY,US,195,NaN,Beach Ave,162,...,"[{'x': -73.86815, 'y': 40.83136}, {'x': -73.86...",6,Westchester Ave,"[{}, {}]",0.705556,2.54,NONE,NONE,1536632605194,2018-09-10T22:23:25.194000
82363,317,1966017277,68186def-08c7-338c-aa7e-0da51e1899f6,Bronx,NY,US,-1,NaN,E 212th St,148,...,"[{'x': -73.878126, 'y': 40.882154}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536137526565,2018-09-05T04:52:06.565000
82364,318,1894915495,7fce4fa0-abf7-3bcc-8d82-5f24441cadc4,Bronx,NY,US,-1,NaN,Jerome Ave,305,...,"[{'x': -73.877607, 'y': 40.884523}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536044634460,2018-09-04T03:03:54.460000
82365,319,1865955143,336d99fc-f463-348f-aa8f-961e7789b290,Bronx,NY,US,-1,NaN,E 211th St,124,...,"[{'x': -73.878487, 'y': 40.881076}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1535991347035,2018-09-03T12:15:47.035000
82366,320,1951777139,011a26a0-706b-3ec3-ac55-4ffaf8e37dbc,Bronx,NY,US,-1,NaN,E 213th St,119,...,"[{'x': -73.877729, 'y': 40.883454}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536137526507,2018-09-05T04:52:06.507000
82367,321,70352023,NaN,Bronx,NY,US,114,NaN,E 221st St,425,...,"[{'x': -73.854323, 'y': 40.886682}, {'x': -73....",2,Bronxwood Ave,"[{}, {}, {}, {}, {}]",2.405556,8.66,NONE,NONE,1536632392713,2018-09-10T22:19:52.713000
82368,322,88002279,NaN,Bronx,NY,US,82,NaN,NaN,929,...,"[{'x': -73.881244, 'y': 40.882709}, {'x': -73....",6,Jerome Ave,"[{}, {}, {}, {}, {}]",4.238889,15.26,NONE,NONE,1536632818380,2018-09-10T22:26:58.380000
82369,323,73470651,NaN,Bronx,NY,US,106,NaN,Laconia Ave,259,...,"[{'x': -73.849488, 'y': 40.889295}, {'x': -73....",1,E 231st St,[{}],1.733333,6.24,NONE,NONE,1536632391543,2018-09-10T22:19:51.543000
82370,324,76832570,NaN,Bronx,NY,US,100,NaN,E 213th St,460,...,"[{'x': -73.865123, 'y': 40.874102}, {'x': -73....",1,Holland Ave,"[{}, {}, {}, {}]",2.494444,8.98,NONE,NONE,1536632392198,2018-09-10T22:19:52.198000
82371,325,69031944,NaN,Bronx,NY,US,66,NaN,Bedford Park Blvd,790,...,"[{'x': -73.896037, 'y': 40.86923}, {'x': -73.8...",7,Jerome Ave,"[{}, {}, {}, {}, {}, {}]",4.688889,16.88,NONE,NONE,1536632746189,2018-09-10T22:25:46.189000
82372,326,73613371,NaN,Bronx,NY,US,82,NaN,Adee Ave,629,...,"[{'x': -73.869215, 'y': 40.875329}, {'x': -73....",1,Barker Ave,"[{}, {}, {}, {}]",2.533333,9.12,NONE,NONE,1536632746947,2018-09-10T22:25:46.947000
82373,327,64213897,NaN,Bronx,NY,US,77,NaN,Grand Concourse,342,...,"[{'x': -73.887635, 'y': 40.872114}, {'x': -73....",7,Bedford Park Blvd (Service Rd),"[{}, {}, {}, {}, {}, {}, {}]",1.738889,6.26,NONE,NONE,1536632747852,2018-09-10T22:25:47.852000
82374,328,88001139,NaN,Bronx,NY,US,79,NaN,W 197th St,189,...,"[{'x': -73.901595, 'y': 40.87414}, {'x': -73.9...",7,Sedgwick Ave,[{}],1.552778,5.59,NONE,NONE,1536632817714,2018-09-10T22:26:57.714000
82375,329,77227208,NaN,Bronx,NY,US,60,NaN,E 212th St,401,...,"[{'x': -73.878039, 'y': 40.887651}, {'x': -73....",6,Jerome Ave,"[{}, {}, {}]",2.927778,10.54,NONE,NONE,1536632533592,2018-09-10T22:22:13.592000
82376,330,76981930,NaN,Bronx,NY,US,71,NaN,E 212th St,230,...,"[{'x': -73.880456, 'y': 40.88222}, {'x': -73.8...",1,Dekalb Ave,[{}],1.547222,5.57,NONE,NONE,1536632817869,2018-09-10T22:26:57.869000
82377,331,64219067,NaN,Bronx,NY,US,100,NaN,Alan Pl,333,...,"[{'x': -73.805916, 'y': 40.81227}, {'x': -73.8...",2,Pennyfield Ave,"[{}, {}, {}, {}, {}, {}, {}, {}]",2.552778,9.19,NONE,NONE,1536632817499,2018-09-10T22:26:57.499000