In [20]:
import pandas as pd
irr = pd.read_csv('data/irr.csv')
al = pd.read_csv('data/al.csv')
jm = pd.read_csv('data/jm.csv')

with open('sample.kml', 'w+') as the_file:
    the_file.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    the_file.write('<kml xmlns="http://earth.google.com/kml/2.1">\n')
    the_file.write('  <Document>\n')
    the_file.write('    <name>NYC Traffic Jams</name>\n')
    the_file.write('    <description>NYC Traffic Jams</description>\n')
    the_file.write('\n')
    the_file.write('    <Style id="redLine">\n')
    the_file.write('      <LineStyle>\n')
    the_file.write('        <color>ff0000ff</color>\n')
    the_file.write('        <width>4</width>\n')
    the_file.write('      </LineStyle>\n')
    the_file.write('    </Style>\n')
    
    for index, row in jm.iterrows(): 
        if row['city'] == "Staten Island":
            the_file.write('          <Placemark>\n')
            the_file.write('          <name>Red Line</name>\n')
            the_file.write('          <styleUrl>#redLine</styleUrl>\n')
            the_file.write('          <LineString>\n')
            the_file.write('            <altitudeMode>relative</altitudeMode>\n')
            the_file.write('            <coordinates>\n')
    
            tokens=row['line'].split("}")
            for word in tokens: 
                the_file.write(word.replace("'y':","").replace("'x':","").replace("[{ ","").replace(", { ","").replace("]",""))
                the_file.write('\n')
     
            the_file.write('            </coordinates>\n')
            the_file.write('          </LineString>\n')
            the_file.write('          </Placemark>\n')
    
    the_file.write('      </Document>\n')
    the_file.write('    </kml>\n')

In [5]:
jm

,Unnamed: 0,uuid,blocking_alert_uuid,city,state,country,delay,start_node,end_node,length,...,line,road_type,street,segments,speed,speed_KMH,turn_type,type,pub_millis,pub_utc_date
0,0,1091249488,NaN,Perth Amboy,NJ,US,169,NaN,NY-440 N / Outerbridge Crossing,2081,...,"[{'x': -74.270613, 'y': 40.526598}, {'x': -74....",3,SR-440 N / Outerbridge Crossing,[{}],8.244444,29.68,NONE,NONE,1530846630171,2018-07-05T23:10:30.171000
1,1,1095145876,NaN,Staten Island,NY,US,116,NaN,NY-440 N,835,...,"[{'x': -74.246496, 'y': 40.524784}, {'x': -74....",3,NY-440 N / Outerbridge Crossing,[{}],5.458333,19.65,NONE,NONE,1530846845855,2018-07-05T23:14:05.855000
2,2,1050403853,32d535c5-4015-3ec2-b8e9-3770525c2540,Elizabeth,NJ,US,-1,NaN,NaN,265,...,"[{'x': -74.189449, 'y': 40.681968}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774199119,2018-07-05T03:03:19.119000
3,3,1014506920,e8f2eb2a-cfb1-314e-9b06-6bf215b77139,Elizabeth,NJ,US,-1,NaN,Earhart Dr,150,...,"[{'x': -74.191085, 'y': 40.681085}, {'x': -74....",1,Basilone Rd,[{}],0.000000,0.00,NONE,NONE,1530687778462,2018-07-04T03:02:58.462000
4,4,936779831,ca3381b7-0941-3146-9462-f68debddf4c6,Elizabeth,NJ,US,-1,NaN,Earhart Dr,374,...,"[{'x': -74.188656, 'y': 40.685938}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530535612023,2018-07-02T08:46:52.023000
5,5,1070660215,1ece3af1-d4c0-3399-a0b6-c05e1adb55a4,Elizabeth,NJ,US,-1,NaN,NaN,90,...,"[{'x': -74.189309, 'y': 40.681168}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774197381,2018-07-05T03:03:17.381000
6,6,1061763046,37069b8a-975a-3dd9-adf2-38b5165344fd,Elizabeth,NJ,US,-1,NaN,NaN,65,...,"[{'x': -74.189072, 'y': 40.684863}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198770,2018-07-05T03:03:18.770000
7,7,1054503000,2d32afd9-0436-3169-9c3c-8d55da7e41c5,Elizabeth,NJ,US,-1,NaN,NaN,60,...,"[{'x': -74.189206, 'y': 40.684333}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198756,2018-07-05T03:03:18.756000
8,8,1053843031,3f89ff35-196a-3ac5-ba2d-1ae19a2b7af9,Elizabeth,NJ,US,-1,NaN,NaN,50,...,"[{'x': -74.188875, 'y': 40.685426}, {'x': -74....",1,Earhart Dr,[{}],0.000000,0.00,NONE,NONE,1530774198764,2018-07-05T03:03:18.764000
9,9,1089266549,NaN,Elizabeth,NJ,US,82,NaN,Basilone Rd,695,...,"[{'x': -74.186058, 'y': 40.675433}, {'x': -74....",1,Earhart Dr,"[{}, {}, {}, {}]",4.625000,16.65,NONE,NONE,1530847058712,2018-07-05T23:17:38.712000
10,10,1089093139,NaN,Brooklyn,NY,US,94,NaN,W 36th St,385,...,"[{'x': -73.998043, 'y': 40.578596}, {'x': -73....",1,Bayview Ave,[{}],2.902778,10.45,NONE,NONE,1530846486099,2018-07-05T23:08:06.099000
11,11,1095083256,NaN,Brooklyn,NY,US,134,NaN,Brighton 4th St,235,...,"[{'x': -73.967344, 'y': 40.580421}, {'x': -73....",6,Neptune Ave,"[{}, {}, {}, {}]",1.325000,4.77,NONE,NONE,1530846625983,2018-07-05T23:10:25.983000
12,12,1091297778,NaN,Brooklyn,NY,US,90,NaN,Coney Island Ave,327,...,"[{'x': -73.96685, 'y': 40.597683}, {'x': -73.9...",6,Ave U,"[{}, {}, {}, {}, {}]",1.877778,6.76,NONE,NONE,1530846773790,2018-07-05T23:12:53.790000
13,13,1104143605,NaN,Brooklyn,NY,US,146,NaN,Ave U,253,...,"[{'x': -73.970056, 'y': 40.599632}, {'x': -73....",1,E 2nd St,[{}],1.338889,4.82,NONE,NONE,1530846777636,2018-07-05T23:12:57.636000
14,14,1095504144,NaN,Queens,NY,US,92,NaN,Rockaway Beach Blvd,201,...,"[{'x': -73.844005, 'y': 40.579516}, {'x': -73....",1,Beach 123rd St,[{}],1.588889,5.72,NONE,NONE,1530846778406,2018-07-05T23:12:58.406000
15,15,1083873923,NaN,Brooklyn,NY,US,68,NaN,Neptune Ave,215,...,"[{'x': -73.957635, 'y': 40.584457}, {'x': -73....",1,E 12th St,"[{}, {}, {}, {}]",1.466667,5.28,NONE,NONE,1530846916953,2018-07-05T23:15:16.953000
16,16,1091359418,NaN,Brooklyn,NY,US,80,NaN,18th Ave,475,...,"[{'x': -73.994847, 'y': 40.604437}, {'x': -73....",1,84th St,"[{}, {}, {}]",2.397222,8.63,NONE,NONE,1530846986866,2018-07-05T23:16:26.866000
17,17,1085620242,NaN,Brooklyn,NY,US,166,NaN,Ave Y,163,...,"[{'x': -73.952581, 'y': 40.58884}, {'x': -73.9...",1,E 17th St,[{}],0.858333,3.09,NONE,NONE,1530846987701,2018-07-05T23:16:27.701000
18,18,1104206385,NaN,Brooklyn,NY,US,100,NaN,Bay 41st St,394,...,"[{'x': -73.989393, 'y': 40.599257}, {'x': -73....",6,86th St,"[{}, {}, {}, {}, {}, {}, {}]",2.563889,9.23,NONE,NONE,1530847058529,2018-07-05T23:17:38.529000
19,19,1083749623,NaN,Brooklyn,NY,US,87,NaN,Cropsey Ave,175,...,"[{'x': -73.998749, 'y': 40.59952}, {'x': -74.0...",1,Bay 28th St,[{}],1.336111,4.81,NONE,NONE,1530846483353,2018-07-05T23:08:03.353000
20,20,1082466902,4efd8189-c26f-30c7-895d-ea43b2c144d6,Bayonne,NJ,US,-1,NaN,NaN,887,...,"[{'x': -74.143173, 'y': 40.639001}, {'x': -74....",3,Bayonne Br N,[{}],0.000000,0.00,NONE,NONE,1530838823113,2018-07-05T21:00:23.113000
21,21,1080769533,00a2486c-467a-3682-9726-c9a874ebff2a,Staten Island,NY,US,-1,NaN,NaN,67,...,"[{'x': -74.143276, 'y': 40.638685}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827240,2018-07-05T21:00:27.240000
22,22,1088789607,062b2fd0-ded3-3840-8560-7df4c651c13b,Bayonne,NJ,US,-1,NaN,NY-440 S / Bayonne Br,890,...,"[{'x': -74.140179, 'y': 40.646674}, {'x': -74....",3,Bayonne Br S,[{}],0.000000,0.00,NONE,NONE,1530838827671,2018-07-05T21:00:27.671000
23,23,1086109869,46853519-cd7d-3eec-9e5e-86c75f9c36f2,Staten Island,NY,US,-1,NaN,Newark Ave,67,...,"[{'x': -74.143937, 'y': 40.638347}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827733,2018-07-05T21:00:27.733000
24,24,1084229941,8cbd6c2d-ce08-3936-b68a-5268a88afd75,Staten Island,NY,US,-1,NaN,Morningstar Rd,87,...,"[{'x': -74.143937, 'y': 40.638347}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827754,2018-07-05T21:00:27.754000
25,25,1082470022,67b17a92-962e-37d9-a4b2-3bea62ae43ae,Staten Island,NY,US,-1,NaN,NaN,87,...,"[{'x': -74.144805, 'y': 40.637932}, {'x': -74....",6,Richmond Ter,[{}],0.000000,0.00,NONE,NONE,1530838827754,2018-07-05T21:00:27.754000
26,26,1095560284,NaN,Staten Island,NY,US,100,NaN,Ocean Ter,725,...,"[{'x': -74.121119, 'y': 40.608338}, {'x': -74....",6,Manor Rd,"[{}, {}, {}, {}, {}, {}, {}, {}, {}]",4.150000,14.94,NONE,NONE,1530846987831,2018-07-05T23:16:27.831000
27,27,941723366,43e37d75-2e75-3d57-8736-630f4501893e,Bayonne,NJ,US,-1,NaN,NaN,173,...,"[{'x': -74.096443, 'y': 40.678433}, {'x': -74....",6,Chosin Few Way,[{}],0.000000,0.00,NONE,NONE,1530528932157,2018-07-02T06:55:32.157000
28,28,1054502550,96145419-0122-31e1-b7ff-26baef289215,Bayonne,NJ,US,-1,NaN,Chosin Few Way,189,...,"[{'x': -74.098521, 'y': 40.677798}, {'x': -74....",2,Peninsula Rd,[{}],0.000000,0.00,NONE,NONE,1530774198610,2018-07-05T03:03:18.610000
29,29,1087960840,NaN,NaN,NaN,US,95,Elizabeth,Newark,247,...,"[{'x': -74.178823, 'y': 40.689952}, {'x': -74....",1,Terminal B Arrivals,[{}],1.227778,4.42,NONE,NONE,1530846776135,2018-07-05T23:12:56.135000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82348,302,77303318,NaN,Bronx,NY,US,82,NaN,Leggett Ave,189,...,"[{'x': -73.90144, 'y': 40.812897}, {'x': -73.8...",7,Southern Blvd,[{}],1.461111,5.26,NONE,NONE,1536632675301,2018-09-10T22:24:35.301000
82349,303,70465113,NaN,Bronx,NY,US,67,NaN,E 161st St,484,...,"[{'x': -73.909874, 'y': 40.815949}, {'x': -73....",1,Cauldwell Ave,"[{}, {}]",3.255556,11.72,NONE,NONE,1536632676193,2018-09-10T22:24:36.193000
82350,304,72871672,NaN,Bronx,NY,US,67,NaN,E 149th St,371,...,"[{'x': -73.913192, 'y': 40.818003}, {'x': -73....",7,Brook Ave,"[{}, {}, {}]",2.833333,10.20,NONE,NONE,1536632746299,2018-09-10T22:25:46.299000
82351,305,64212227,NaN,Bronx,NY,US,76,NaN,Seward Ave,542,...,"[{'x': -73.868276, 'y': 40.82342}, {'x': -73.8...",1,Noble Ave,"[{}, {}, {}, {}]",2.275000,8.19,NONE,NONE,1536632746838,2018-09-10T22:25:46.838000
82352,306,77304408,NaN,Bronx,NY,US,98,NaN,Bronxdale Ave,254,...,"[{'x': -73.866996, 'y': 40.848673}, {'x': -73....",1,Cruger Ave,[{}],1.563889,5.63,NONE,NONE,1536632676050,2018-09-10T22:24:36.050000
82353,307,87965859,NaN,Bronx,NY,US,218,NaN,Jennings St,201,...,"[{'x': -73.889727, 'y': 40.834058}, {'x': -73....",6,Southern Blvd,[{}],0.794444,2.86,NONE,NONE,1536632676156,2018-09-10T22:24:36.156000
82354,308,68065815,NaN,Bronx,NY,US,65,NaN,E 188th St,590,...,"[{'x': -73.894414, 'y': 40.866037}, {'x': -73....",6,Grand Concourse,"[{}, {}, {}, {}]",4.772222,17.18,NONE,NONE,1536632676696,2018-09-10T22:24:36.696000
82355,309,64211007,NaN,Bronx,NY,US,91,NaN,W 190th St,230,...,"[{'x': -73.900596, 'y': 40.866349}, {'x': -73....",1,Grand Ave,[{}],1.677778,6.04,NONE,NONE,1536632746018,2018-09-10T22:25:46.018000
82356,310,65741686,NaN,Bronx,NY,US,104,NaN,E 169th St,555,...,"[{'x': -73.903337, 'y': 40.837641}, {'x': -73....",7,Washington Ave,"[{}, {}, {}]",3.022222,10.88,NONE,NONE,1536632817690,2018-09-10T22:26:57.690000
82357,311,72879652,NaN,Bronx,NY,US,76,NaN,Stillwell Ave,593,...,"[{'x': -73.845917, 'y': 40.857353}, {'x': -73....",2,Pelham Pkwy S (Service Rd),"[{}, {}]",2.897222,10.43,NONE,NONE,1536632817737,2018-09-10T22:26:57.737000
82358,312,70501093,NaN,Bronx,NY,US,100,NaN,Grand Concourse (Service Rd),250,...,"[{'x': -73.909174, 'y': 40.849899}, {'x': -73....",1,E 177th St,"[{}, {}]",1.463889,5.27,NONE,NONE,1536632818205,2018-09-10T22:26:58.205000
82359,313,70504003,NaN,Bronx,NY,US,78,NaN,Westchester Ave,219,...,"[{'x': -73.831132, 'y': 40.845307}, {'x': -73....",7,Crosby Ave,[{}],1.441667,5.19,NONE,NONE,1536632819685,2018-09-10T22:26:59.685000
82360,314,65697706,NaN,Bronx,NY,US,107,NaN,E 186th St,227,...,"[{'x': -73.894412, 'y': 40.855813}, {'x': -73....",1,Park Ave,"[{}, {}, {}]",1.730556,6.23,NONE,NONE,1536632605084,2018-09-10T22:23:25.084000
82361,315,63695107,NaN,Bronx,NY,US,77,NaN,Westchester Ave,286,...,"[{'x': -73.876993, 'y': 40.831514}, {'x': -73....",1,Manor Ave,[{}],1.658333,5.97,NONE,NONE,1536631390366,2018-09-10T22:03:10.366000
82362,316,68996254,NaN,Bronx,NY,US,195,NaN,Beach Ave,162,...,"[{'x': -73.86815, 'y': 40.83136}, {'x': -73.86...",6,Westchester Ave,"[{}, {}]",0.705556,2.54,NONE,NONE,1536632605194,2018-09-10T22:23:25.194000
82363,317,1966017277,68186def-08c7-338c-aa7e-0da51e1899f6,Bronx,NY,US,-1,NaN,E 212th St,148,...,"[{'x': -73.878126, 'y': 40.882154}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536137526565,2018-09-05T04:52:06.565000
82364,318,1894915495,7fce4fa0-abf7-3bcc-8d82-5f24441cadc4,Bronx,NY,US,-1,NaN,Jerome Ave,305,...,"[{'x': -73.877607, 'y': 40.884523}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536044634460,2018-09-04T03:03:54.460000
82365,319,1865955143,336d99fc-f463-348f-aa8f-961e7789b290,Bronx,NY,US,-1,NaN,E 211th St,124,...,"[{'x': -73.878487, 'y': 40.881076}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1535991347035,2018-09-03T12:15:47.035000
82366,320,1951777139,011a26a0-706b-3ec3-ac55-4ffaf8e37dbc,Bronx,NY,US,-1,NaN,E 213th St,119,...,"[{'x': -73.877729, 'y': 40.883454}, {'x': -73....",7,Bainbridge Ave,[{}],0.000000,0.00,NONE,NONE,1536137526507,2018-09-05T04:52:06.507000
82367,321,70352023,NaN,Bronx,NY,US,114,NaN,E 221st St,425,...,"[{'x': -73.854323, 'y': 40.886682}, {'x': -73....",2,Bronxwood Ave,"[{}, {}, {}, {}, {}]",2.405556,8.66,NONE,NONE,1536632392713,2018-09-10T22:19:52.713000
82368,322,88002279,NaN,Bronx,NY,US,82,NaN,NaN,929,...,"[{'x': -73.881244, 'y': 40.882709}, {'x': -73....",6,Jerome Ave,"[{}, {}, {}, {}, {}]",4.238889,15.26,NONE,NONE,1536632818380,2018-09-10T22:26:58.380000
82369,323,73470651,NaN,Bronx,NY,US,106,NaN,Laconia Ave,259,...,"[{'x': -73.849488, 'y': 40.889295}, {'x': -73....",1,E 231st St,[{}],1.733333,6.24,NONE,NONE,1536632391543,2018-09-10T22:19:51.543000
82370,324,76832570,NaN,Bronx,NY,US,100,NaN,E 213th St,460,...,"[{'x': -73.865123, 'y': 40.874102}, {'x': -73....",1,Holland Ave,"[{}, {}, {}, {}]",2.494444,8.98,NONE,NONE,1536632392198,2018-09-10T22:19:52.198000
82371,325,69031944,NaN,Bronx,NY,US,66,NaN,Bedford Park Blvd,790,...,"[{'x': -73.896037, 'y': 40.86923}, {'x': -73.8...",7,Jerome Ave,"[{}, {}, {}, {}, {}, {}]",4.688889,16.88,NONE,NONE,1536632746189,2018-09-10T22:25:46.189000
82372,326,73613371,NaN,Bronx,NY,US,82,NaN,Adee Ave,629,...,"[{'x': -73.869215, 'y': 40.875329}, {'x': -73....",1,Barker Ave,"[{}, {}, {}, {}]",2.533333,9.12,NONE,NONE,1536632746947,2018-09-10T22:25:46.947000
82373,327,64213897,NaN,Bronx,NY,US,77,NaN,Grand Concourse,342,...,"[{'x': -73.887635, 'y': 40.872114}, {'x': -73....",7,Bedford Park Blvd (Service Rd),"[{}, {}, {}, {}, {}, {}, {}]",1.738889,6.26,NONE,NONE,1536632747852,2018-09-10T22:25:47.852000
82374,328,88001139,NaN,Bronx,NY,US,79,NaN,W 197th St,189,...,"[{'x': -73.901595, 'y': 40.87414}, {'x': -73.9...",7,Sedgwick Ave,[{}],1.552778,5.59,NONE,NONE,1536632817714,2018-09-10T22:26:57.714000
82375,329,77227208,NaN,Bronx,NY,US,60,NaN,E 212th St,401,...,"[{'x': -73.878039, 'y': 40.887651}, {'x': -73....",6,Jerome Ave,"[{}, {}, {}]",2.927778,10.54,NONE,NONE,1536632533592,2018-09-10T22:22:13.592000
82376,330,76981930,NaN,Bronx,NY,US,71,NaN,E 212th St,230,...,"[{'x': -73.880456, 'y': 40.88222}, {'x': -73.8...",1,Dekalb Ave,[{}],1.547222,5.57,NONE,NONE,1536632817869,2018-09-10T22:26:57.869000
82377,331,64219067,NaN,Bronx,NY,US,100,NaN,Alan Pl,333,...,"[{'x': -73.805916, 'y': 40.81227}, {'x': -73.8...",2,Pennyfield Ave,"[{}, {}, {}, {}, {}, {}, {}, {}]",2.552778,9.19,NONE,NONE,1536632817499,2018-09-10T22:26:57.499000